language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm test
  - npm run example:default
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'